name: Wicked Cool Words
description: Probably the best vocabulary blog on the internet
author: David Howland
author: wickedcoolwords@frigidlight.com
markdown: rdiscount
permalink: pretty
url: http://wickedcoolwords.org
