name: Wicked Cool Words
description: Probably the best vocabulary blog on the internet
author: David Howland
author: wickedcoolwords@frigidlight.com
permalink: pretty
url: http://wickedcoolwords.org
gems: ['jekyll-twitter-plugin']
timezone: America/New York
